# Project configuration
site_name: Alessandro Biagiotti's portfolio
site_url: https://S3gmentati0nFault.github.io/
site_author: Alessandro Biagiotti
site_description: >-
  I'm Alessandro Biagiotti master student of Computer Science at the University of Milan.

theme:
  name: material

nav:
  - Home: index.md
  - Latest project:
      - "Deployment of LLMs at the edge of the 6G network": deployment_of_llms_in_6G_networks/readme.md
  - Old projects:
      - "Anomaly detection": autoencoders/readme.md
      - "Greenfield": greenfield/readme.md
      - "Algoweb": algoweb/readme.md
      - "Discrete structures 1": structures/readme.md
      - "Pump down the flame": vdp/readme.md
