# Project configuration
site_name: Alessandro Biagiotti's portfolio
site_url: https://S3gmentati0nFault.github.io/
site_author: Alessandro Biagiotti
site_description: >-
  I'm Alessandro Biagiotti master student of Computer Science at the University of Milan.

theme:
  name: material

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Latest project:
      - "Deployment of LLMs at the edge of the 6G network": deployment_of_llms_in_6G_networks/readme.md
  - Older projects:
      - "Anomaly detection": autoencoders/readme.md
      - "Greenfield": greenfield/readme.md
      - "Bachelor Thesis": bachelor/readme.md
      - "Pump down the flame": vdp/readme.md
      - "Algoweb": algoweb/readme.md
      - "Discrete structures 1": structures/readme.md
  - Me:
      - "Curriculum": me/curriculum.md
      - "Passions": me/passions.md
      - "Overhear podcast": me/podcast.md
      - "Erasmus": me/erasmus.md
      - "University of Milan": me/unimi.md
      - "University of Milan Bicocca": me/unimib.md
      - "Polytechnic university of Milan": me/polimi.md
